#!/usr/bin/env php
<?php

namespace jack\cmd;

$composerAutoload = [
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../../autoload.php',
];
foreach ($composerAutoload as $autoload) {
    if (file_exists($autoload)) {
        require($autoload);
        break;
    }
}

$parser = new ColoredMarkdownCLI();

if (php_sapi_name() === 'cli') {
    if ($argc > 1)
        $markdown = file_get_contents($argv[1]);
    else
        $markdown = stream_get_contents(STDIN);
    echo $parser->parse($markdown);
} else {
    die();
}
